sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: XQzmlZ1eK7hR2QsfrVyOFIzFmIGTBvJ2kiq/lVVub5yyf73PfpvEN1v3EKX0ugVqh7PxbDlBpu5WaURBqeTt64XUYCxQZRBb+l/ZTzoasJ2g+KDq/Q5LzImSkUlRjpSzp59Tppacum8z4ZOUt7tCWI1d/Apj6f3Xktvrzo5z9Byd8KwaOLgyBrg2jf1Z3mJxd6Rj4xyd3QL2fC9+d5uaHf6PLhJDGg0LF2xDVzFabdxSJyIyjaSFWjl6FB95Cd6Q/Rb4g50T5cEygy5PAllb/NdyoXXC5aI7LME73WBzGLlopZa5WnQUFRwevFkR7rXWa6AR4k73zvCo0gExOPjmCXtEie1Vrc9+7mKqEDjOEZsP/JIGMV52H80FRHh2By3QhPQu62oteiU5Zv+Gj8F5ZsUyaZ/b2PDE1m4M8hCfMnv/DIS0Pg3PAd0BSXfZdYGDPkd+KXNPM9Y46nkIAWPKZM6pfJ6qtmDRfiqFghTBMvws7atUPrETt7dWGlk/OPrftAcWIETjIpaU9Of9QzLRvGbRxpiMpaqB4IpYk+PdD+my3J9f3LRIWhbFuFn/PEyIvtZ1bVoYv4xw53+mqS6usde2kMyWTi+dfEmN/VhoE0ZODxagRCniu+yF1HuX6xlSMjQwZ0nUL+/7AjEkDdjLsnIURwDRsEaYHoqtZV/LXCM=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Comedy-of-Errors_1769
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy